In [194]:
#import Pool
from multiprocessing import Pool


In [195]:
import numpy as np

In [196]:
import importlib

In [197]:
import functions

In [198]:
import time

In [206]:
try:
    importlib.reload(functions)
except:
    import functions

In [208]:
y = 3

In [209]:
functions.worker(a)

NameError: name 'y' is not defined

In [177]:
#Assuming you want to use 3 processors
num_processors = 12


In [178]:
#Create a pool of processors
p=Pool(processes = num_processors)


In [202]:
a = np.arange(1000)


In [182]:
start_time = time.time()

q = np.array([])
for i in [a]:
    q = np.append(q, functions.worker(3,i))
    
print(time.time() - start_time)

C:\Users\Chirag\Machine learning\Version1(oct2021)\functions.py:8: RuntimeWarning: overflow encountered in long_scalars
  return container


20.748656034469604


In [183]:
tasks = np.array_split(a,12)

In [184]:
qz = np.ones(len(tasks))[:] 
qz[:] = 3

In [185]:
qz

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [186]:
obj = zip(qz, tasks)

In [187]:
obj

In [188]:
#get them to work in parallel
start_time = time.time()
output = p.starmap(functions.worker,obj)

print(time.time() - start_time)

0.7371652126312256


In [189]:
for i in output:
    np

[array([0.0000000e+00, 3.0000000e+00, 1.0000000e+00, ..., 3.0000000e+00,
        6.9438889e+07, 3.0000000e+00]),
 array([6.94555560e+07, 3.00000000e+00, 6.94722250e+07, ...,
        3.00000000e+00, 2.77788889e+08, 3.00000000e+00]),
 array([2.77822224e+08, 3.00000000e+00, 2.77855561e+08, ...,
        3.00000000e+00, 6.25050001e+08, 3.00000000e+00]),
 array([6.25100004e+08, 3.00000000e+00, 6.25150009e+08, ...,
        3.00000000e+00, 1.11122222e+09, 3.00000000e+00]),
 array([1.11128890e+09, 3.00000000e+00, 1.11135557e+09, ...,
        3.00000000e+00, 1.73622222e+09, 3.00000000e+00]),
 array([ 1.73630556e+09,  3.00000000e+00,  1.73638890e+09, ...,
         3.00000000e+00, -1.79486730e+09,  3.00000000e+00]),
 array([-1.79476729e+09,  3.00000000e+00, -1.79466729e+09, ...,
         3.00000000e+00, -8.92111740e+08,  3.00000000e+00]),
 array([-8.91995071e+08,  3.00000000e+00, -8.91878400e+08, ...,
         3.00000000e+00,  1.49521593e+08,  3.00000000e+00]),
 array([1.49654928e+08, 3.00000000e+

In [161]:
output

[]

In [113]:
output

[]

In [40]:
start_time = time.time()

result = np.array(output)

print(time.time() - start_time)

0.0


<ipython-input-40-0fb5d7bf2227>:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  result = np.array(output)


In [72]:
output

[array([0.0000000e+00, 1.0000000e+00, 4.0000000e+00, ..., 6.9405561e+07,
        6.9422224e+07, 6.9438889e+07]),
 array([6.94555560e+07, 6.94722250e+07, 6.94888960e+07, ...,
        2.77722225e+08, 2.77755556e+08, 2.77788889e+08]),
 array([2.77822224e+08, 2.77855561e+08, 2.77888900e+08, ...,
        6.24950001e+08, 6.25000000e+08, 6.25050001e+08]),
 array([6.25100004e+08, 6.25150009e+08, 6.25200016e+08, ...,
        1.11108889e+09, 1.11115556e+09, 1.11122222e+09]),
 array([1.11128890e+09, 1.11135557e+09, 1.11142224e+09, ...,
        1.73605556e+09, 1.73613889e+09, 1.73622222e+09]),
 array([ 1.73630556e+09,  1.73638890e+09,  1.73647224e+09, ...,
        -1.79506730e+09, -1.79496730e+09, -1.79486730e+09]),
 array([-1.79476729e+09, -1.79466729e+09, -1.79456728e+09, ...,
        -8.92345072e+08, -8.92228407e+08, -8.92111740e+08]),
 array([-8.91995071e+08, -8.91878400e+08, -8.91761727e+08, ...,
         1.49254929e+08,  1.49388260e+08,  1.49521593e+08]),
 array([1.49654928e+08, 1.49788265e+

In [190]:
z = np.array([])
start_time = time.time()
for i in output:
    z = np.append(z, i)
print(time.time() - start_time)
"""
;lsdfl;sd;lf,

;ls"""

0.0030007362365722656


'\n;lsdfl;sd;lf,\n\n;ls'

In [193]:
np.sum(z != q)

0